### ISSUE TITLE
BnCert-Tool unexpected behavior.

### ISSUE THREAD

**Issue by PaerToernell** [bitnami/bncert#24]
### What steps will reproduce the bug?

1. Setup with lightsail LAMP
2. Add multiple domains in the /opt/bitnami/apache/conf/vhosts/

### What is the expected behavior?

Expected behavior is that ssl directs according to settings in vhosts. after using BnCert-Tool.

### What do you see instead?

BnCert-Tool ignores v-host and put some links to the certificates in "/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf". I have to manually do the adjustments and put the links in the v-hosts.

**Comment by gongomgra** [comment]
Hi @PaerToernell,

Thanks for using Bitnami. The bncert tool generates one single SSL certificate, and it configures it in the global Apache config file so all other virtualhosts inherit its usage unless specified otherwise in a given virtualhost. In case you need to use a single certificate per virtualhost, please refer to our [custom applications](https://docs.bitnami.com/aws/apps/wordpress/administration/create-custom-application-php/) and [alternative approach](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach) guides, just do not create the symbolic links in the SSL guide and point the `SSLCertificateFile` and `SSLCertificateKeyFile` directives to the generated files instead of the common ones. Remember to check filesystem permissions so Apache can access your certificates.

Hope it helps!
